version: "3"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chat_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_HOST_AUTH_METHOD: trust

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data:
